### ISSUE TITLE
PCB 1.04 but no schematic 1.04

### ISSUE THREAD

**Issue by beamzer** [JanDerogee/TeleJukebox#4]
Hi, I got a PCB version 1.04 which i was soldering, but it seems that this version is not completely compatible with the 1.03 schematic? In 1.03 i see some resistors which are not the on the PCB. Can you help out?

TIA,
Ewald...

**Comment by JanDerogee** [comment]
Hello Ewald,
I didn't make the PCB myself, somebody else made it, so I don't have access to the schematic files.
Hoewever the differences are very small. The 1.04 version doesn't have an power LED, it doesn't have a reset button and it doesn't have a jumper.
The jumper was intended for debugging purposes, but the code doesn't need this jumper to run.
The reset button was intended for debugging purposes, but the code doesn't need this jumper to run.
The power LED was for fun, but you don't really need it. The other LED which is connected to an IO-pin is much more usefull. So to save space the LED thta only indicated power was removed from the board to save space and power.

I hope this info is helpfull,
kind regards,
Jan

________________________________

**Comment by beamzer** [comment]
I checked with Paul who designed the v1.04 and he said that the resistor values are just the same as v1.03 and R8, R9 and R10 are left out on purpose.
