### ISSUE TITLE
TeleJukbox maken 

### ISSUE THREAD

**Issue by bartgubbels11** [JanDerogee/TeleJukebox#5]
Hallo Jan,  

Het is mij gelukt om de T65 met draaischijf werkend te krijgen (: 

Ik ben nu bezig om een T65 TDK om te zetten naar en Telejukbox. Het verschil is dus dat de T65 TDK werkt met toon (DTMF) in plaats van pulse. Als ik een draaischijf op de t65 TDK zet werkt de telejukbox wel. Ik zou echter graag willen dat de T65 TDK met toetsen ook werkt. 

Is er misschien een manier om de toon om te zetten naar een pulse signaal of is dat niet mogelijk.
Of zou ik de file van arduino kunnen aanpassen waardoor dit wel zou kunnen werken. Ik heb zelf niet heel veel verstand van arduino dus misschien dat u dat wel Kan/weet? 

Ik hoor het wel!

Met vriendelijke groet,

Bart

**Comment by JanDerogee** [comment]
Hallo Bart,
goed om te horen dat je de telejukebox heb gebouwd en dat het lijkt te werken.
Met zo'n oude telefoon kan er immers een hoop mis zijn.

De telejukebox ondersteund geen DTMF oftewel geen toonkiezen.
Het vergt flinke aanpassingen in de firmware (arduino code) EN in de hardware!

Het probleem zit 'm in de toon, dit is een analoog signaal, oftewel audio. In het geval van de draaischijf is het een puur digitaal signaal. Er is wel of er is geen puls, dat is bijzonder eenvoudig detecteerbaar en dus veel gemakkelijker te programmeren dan continue luisteren of er een toon is. Omdat de charme van de telejukebox voor een groot deel in de draaischijf zit EN in het intact laten van de telefoon. Heb ik dan ook geen enkele moeite gestoken in het ondersteunen van DTMF. En dus heb ik de hardware zo eenvoudig mogelijk gemaakt zodanig dat deze eigenlijk alleen werkt voor pulskiezen. Ik heb verder ook geen ambities om DTMF te ondersteunen. Op het moment dat ik dat zou doen ben ik bijna een telefoon centrale aan het bouwen en dat ging me wat te ver.

Ik hoop dat dit een beetje duidelijk is, maar in de basis is DTMF vele malen complexer dan pulskiezen.

Met vriendelijke groet
Jan Derogee.

________________________________

**Comment by bartgubbels11** [comment]
Hallo Jan,

Heel erg bedankt voor de snelle reactie!

Dus als ik het goed begrijp is daar eigenlijk geen beginnen aan. Ik zie dat je een puls signaal met een converter over kan zetten naar toon kiezen (DTMF). Is het dan niet op een of andere manier mogelijk om dat andersom te krijgen door bijvoorbeeld een converter of iets dergelijks toepast . 

Ik hoor het wel

Met vriendelijke groet,

Bart Gubbels

**Comment by JanDerogee** [comment]
Hallo bart,
Het klinkt logisch om een toon signaal om te zetten naar een puls signaal m.b.v. een losse converter schakeling. Echter ik heb hier geen ervaring mee. Het is ook niet een veelvoorkomend probleem, immers het is een stap terug in techniek, het levert geen snelheidswinst op en er is geen goede reden waarom er een dergelijke schakeling al zou bestaan. Iets dat gewoon te koop is bedoel ik dan. Maar aan de andere kant, ik heb het wel vaker mis...
Om een lang verhaal kort te maken, ik weet het niet. Maar mocht je toch zo'n converter weten te vinden dan Jan ik geen garantie geven dat het ook werkt met de telejukebox. Er is immers een grote kans dat de telefoon aan 5volt niet genoeg heeft en geen tonen wil genereren. Maar ook dat weet ik niet.

Kortom, ik Jan je hier niet echt verder mee helpen.
Groeten, Jan.

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________

**Comment by JanDerogee** [comment]
case closed
